# Setup
title:               Toffs CDN
tagline:             'C4 project'
description:         'Toffs Technologies PTE .LTD document for CDN.'
url:                 https://support.toffstech.net
baseurl:             ''
paginate:            5
permalink:           /:categories/:title/

# About/contact
author:
  name:              Toffs Technologies
  url:               https://twitter.com/toffstech
  email:             dev-long@toffstech.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
