# Setup
title:               ToffsCDN
tagline:             'C4 project'
description:         'Toffs Technologies PTE .LTD document for CDN.'
url:                 https://toffs-dev.github.io/c4_support_document/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/toffstech
  email:             dev-long@toffstech.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
